sudo: required

language: go

go:
    - 1.13.x

service:
    - docker
    
install: 
    - echo "build serve"
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install -U pytest
    
before_script:
    - go get -u golang.org/x/lint/golint
    - wget https://raw.githubusercontent.com/smartfog/fogflow/master/docker/core/http/docker-compose.yml
    - wget https://raw.githubusercontent.com/smartfog/fogflow/master/docker/core/http/config.json
    - wget https://raw.githubusercontent.com/smartfog/fogflow/master/docker/core/http/nginx.conf
    - wget https://raw.githubusercontent.com/smartfog/fogflow/master/docker/core/http/metricbeat.docker.yml
    - sudo docker-compose pull 
    - sudo docker-compose up -d
    - sudo docker ps -a

script:
    - go build serve.go
    - echo "build successful"
    - cd v2
    - pytest -s -v 
    
after_script:
    - sudo docker stop fogflow/discovery:3.0 
    - sudo docker stop fogflow/broker:3.0

notifications:
    email: false
