sudo: required

language: go

go:
    - 1.13.x

install: 
    - echo "build serve"
    - cd ../serve
    - pwd
    - sh build    

before_script:
    - go get -u golang.org/x/lint/golint


script:

notifications:
    email: false
