sudo: required

language: go

go:
    - 1.13.x
    
install: 
    - echo "build serve"
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - apt-cache policy docker-ce
    - sudo apt-get install -y docker-ce
    - sudo systemctl status docker
    - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install requests 
    - pip install jsonlib
    - pip install -U pytest
        
before_script:
    - go get -u golang.org/x/lint/golint
    - go build serve.go
       
script:
    - screen -d -m ./serve
    - cd script
    - pytest -s -v
    
after_script:
    
notifications:
    email: false
