sudo: required

language: go

go:
    - 1.13.x

service:
    - docker
    
install: 
    - echo "build serve"
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install requests 
    - pip install -U pytest
    
    
before_script:
    - go get -u golang.org/x/lint/golint
    - go build serve.go
       
script:
    - sh try.sh
    
after_script:
    
notifications:
    email: false
