sudo: required

language: go

go:
    - 1.13.x

install: 
    - echo "build serve"

before_script:
    - go get -u golang.org/x/lint/golint


script:
    - go build serve.go
    ./serve
    

notifications:
    email: false
