sudo: required

language: go

go:
    - 1.13.x

install: 
    - echo "build serve"
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install requests 
    - pip install -U pytest
    
    
before_script:
    - go get -u golang.org/x/lint/golint
    - go build serve.go
       
script:
    - cd v2
    - pytest -v -s 
    
after_script:
    
notifications:
    email: false
