sudo: required

language: go

go:
    - 1.13.x

service:
    - docker
    
install: 
    - echo "build serve"
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - python2 pip install --upgrade pip
    - pip install -U pytest
    
before_script:
    - go get -u golang.org/x/lint/golint
    - docker pull 9beeba249f3e
    - docker pull rabbitmq:3 
    - docker pull fogflow/discovery:3.0
    - docker pull fogflow/broker:3.0

script:
    - go build serve.go
    - echo "build successful"
    - docker run 9beeba249f3e 
    - docker run rabbitmq:3
    - docker run fogflow/discovery:3.0
    - docker run fogflow/broker:3.0
    - docker ps -a
    - cd v2
    - pytest -s -v 
    
after_script:
    - docker stop 9beeba249f3e
    - docker stop rabbitmq:3
    - docker stop fogflow/discovery:3.0
    - docker stop fogflow/broker:3.0

notifications:
    email: false
