sudo: required

language: go

go:
    - 1.13.x

service:
    - docker
    
install: 
    - echo "build serve"
    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install -U pytest
    
before_script:
    - go get -u golang.org/x/lint/golint
    - sudo docker pull fogflow/discovery:3.0
    - sudo docker pull fogflow/broker:3.0

script:
    - go build serve.go
    - echo "build successful"
    - sudo docker run fogflow/discovery:3.0 
    - sudo docker fogflow/broker:3.0
    - sudo docker ps -a
    - cd v2
    - pytest -s -v 
    
after_script:
    - sudo docker stop fogflow/discovery:3.0 
    - sudo docker stop fogflow/broker:3.0

notifications:
    email: false
